name: Deploy

on:
  push:
    branches:
      - main
      - dev
permissions:
  id-token: write
  contents: read
jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-to-env.yml
    with:
      environment: production
    secrets:
      aws_role_arn: ${{ secrets.AWS_GITHUB_OIDC_PROVIDER_SYNC_ROLE_ARN }}
      s3_bucket_name: ${{ secrets.S3_BUCKET_NAME }}
      cloudfront_distribution_id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/deploy-to-env.yml
    with:
      environment: development
    secrets:
      AWS_GITHUB_OIDC_PROVIDER_SYNC_ROLE_ARN: ${{ secrets.AWS_GITHUB_OIDC_PROVIDER_SYNC_ROLE_ARN }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
